resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Patching ConfigMap for dev environment
configMapGenerator:
  - name: webapp-config
    behavior: merge
    literals:
      - APP_ENV=development
      - LOG_LEVEL=debug

# Patching Secret for dev environment
secretGenerator:
  - name: webapp-secrets
    behavior: merge
    literals:
      - DB_PASSWORD=ZGV2cGFzc3dvcmQ=        # 'devpassword'
      - API_KEY=ZGV2YXBpa2tleQ==            # 'devapikey'
