# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
type: Opaque
data:
  DB_PASSWORD: c2VjcmV0cGFzc3dvcmQ=     # Base64-encoded secret (e.g., 'secretpassword')
  API_KEY: c2VjcmV0YXBpa2V5              # Base64-encoded API key
