apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap6-deployment  # Name of the deployment
spec:
  replicas: 1  # Number of replicas (pods) you want to run
  selector:
    matchLabels:
      app: cap6-web  # The label selector to identify the pods managed by this deployment
  template:
    metadata:
      labels:
        app: cap6-web  # Label to identify the pods created by this deployment
    spec:
      containers:
      - name: cap6-container  # Name of the container
        image: micgreat/capstone6:1.0  # Docker image for the container
        ports:
        - containerPort: 80  # Port that the container will expose
